version: '3.2'

services:
  elasticsearch:
    image: testing_plugin_install
    build: 
     context: .
     dockerfile: ./Dockerfile
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - script.allowed_types=inline
      - script.allowed_contexts=filter